# This is a basic workflow to help you get started with Actions

name: Testing Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test1" ]
  pull_request:
    branches: [ "test1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.1
        
      - name: Setup NuGet.exe for use with actions
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@795d81930e6f583d6dbe984a5634efe5de9e54a7
        uses: NuGet/setup-nuget@v1.0.7
        
      - name: Restore NuGet packages
        run: nuget restore BugGuardian.MVC-master\BugGuardian.MVC.sln
        
      - name: Build the Solution
        run: msbuild BugGuardian.MVC-master\BugGuardian.MVC.sln
