# This is a basic workflow to help you get started with Actions

name: Testing Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test1" ]
  pull_request:
    branches: [ "test1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with: 
              persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
              fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        
        
      - name: Setup NuGet.exe for use with actions
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@795d81930e6f583d6dbe984a5634efe5de9e54a7
        uses: nuget/setup-nuget@main

        
      - name: Restore NuGet packages
        run: nuget restore C-Sharp-master\C-Sharp.sln
        
      - name: Build the Solution
        run: msbuild C-Sharp-master\C-Sharp.sln
                          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3.1.0
        with:
           name: BuildResult
           path: D:\a\Testing-for-automation\Testing-for-automation\C-Sharp-master\Utilities.Tests\bin
           

          
  scan:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
        with: 
          java-version: '8'
          
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with: 
              name: BuildResult
              path: C-Sharp-master/BuildResult
        env:
          GITHUB_TOKEN: ${{ github.token }}    
          
      
      - name: Veracode Upload And Scan
        # You may pin to the exact commit or the version.
        #uses: veracode/veracode-uploadandscan-action@35794dab9fbcd28fac19e44963f80646b27f4a7f
        #uses: veracode/veracode-uploadandscan-action@0.2.4
        uses: veracode/veracode-uploadandscan-action@master
        with:
          # appname
          appname: "${{ github.repository }}"
          # filepath
          filepath: "/home/runner/work/Testing-for-automation/Testing-for-automation/C-Sharp-master/BuildResult"
          # version
          version: "${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
          # vid
          vid: "$vid"
          # vkey
          vkey: "$vkey"
          # true or false
          sandboxname: "Odin2_sandbox"
          # wait X minutes for the scan to complete
          include: "*.dll"
          # teams
          teams: "Diagnostics"
          # automatically delete the current scan if there are any errors when uploading files or starting the scan
          deleteincompletescan: false
          # specify version of the Java API Wrapper; default is latest
          #javawrapperversion: "v22.6.10.2"
        env:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_SECRET }}
           
      
